# Generated by Django 2.0.2 on 2018-02-25 20:12

import CustomMusic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('time', models.IntegerField(default=CustomMusic.models.rightnow)),
            ],
        ),
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('time', models.IntegerField(default=CustomMusic.models.rightnow)),
            ],
        ),
    ]
