# Generated by Django 2.0.2 on 2018-02-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomMusic', '0001_RoomEntry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelEntry',
            new_name='FloorEntry',
        ),
    ]
